defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Samuel Hierholzer"
  - scope:
      path: ""
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship

page_excerpts: true

jekyll-spaceship:
  processors:
    - mermaid-processor
    - emoji-processor
    - media-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    config:
      theme: forest

permalink: /:title/
